all:
	g++ main.cpp -g -o main \
        -lglfw -lGLU -lGL -lGLEW 
		-I dependencies/include/ 
		-L dependencies/library 
		$./dependencies/library/libglfw.3.3.dylib
		-framework 
		OpenGL
		-framework 
		IOKit
		-framework 
		CoreVideo
		-framework 
		CoreFoundation
		-framework 
		OpenGL

