# -*- mode: ruby -*-
# vi: set ft=ruby :
# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don’t change it unless you know what
# you’re doing.
Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/jammy64"
    # config.vm.synced_folder line is commented out, you can edit it
    config.vm.synced_folder "./code", "/home/vagrant/code", type: "rsync"
    # the rest of the file is commented out and is not important
end
