[package]
name = "your_project_name"
version = "0.1.0"
edition = "2018"

[dependencies]
digest = "0.9.0"
blake2 = "0.10.1"
chrono = "0.4"
jsonwebtoken = "7.2.0"
ring = "0.16"
serde_json = "1.0"
blake2-rfc = "0.2.18"
serde = { version = "1.0", features = ["derive"] }
reqwest = { version = "0.10.0-alpha.2", features = ["blocking"] }
tokio = { version = "1", features = ["full"] }
